export const MOCK_ORGANIZATIONS = [
  {
    id: "1",
    name: "Acme Corp",
    slug: "acme-corp",
    role: "Admin",
    status: "active",
    members: 12,
    createdAt: "2024-01-15",
    logo: null,
  },
  {
    id: "2",
    name: "Globex Corporation",
    slug: "globex",
    role: "Member",
    status: "active",
    members: 45,
    createdAt: "2023-11-20",
    logo: null,
  },
  {
    id: "3",
    name: "Soylent Corp",
    slug: "soylent",
    role: "Admin",
    status: "pending",
    members: 3,
    createdAt: "2024-02-01",
    logo: null,
  },
  {
    id: "4",
    name: "Umbrella Academy",
    slug: "umbrella",
    role: "Viewer",
    status: "inactive",
    members: 8,
    createdAt: "2023-08-10",
    logo: null,
  },
  {
    id: "5",
    name: "Cyberdyne Systems",
    slug: "cyberdyne",
    role: "Admin",
    status: "active",
    members: 156,
    createdAt: "2024-01-05",
    logo: null,
  },
] as const;
