import type { ActionDefinition } from "@/registry/types";

export const actionRegistry: ActionDefinition[] = [
  {
    id: "add-product",
    label: "Add Product",
    description: "Add a new item to inventory",
    keywords: ["add", "product", "inventory", "new", "item", "stock", "create"],
    category: "inventory",
    blockId: "products",
    icon: "package-plus",
    formId: "add-product",
    requiresConfirm: false,
    usageWeight: 10,
  },
  {
    id: "edit-product",
    label: "Edit Product",
    description: "Update product details or pricing",
    keywords: ["edit", "update", "product", "change", "modify", "stock"],
    category: "inventory",
    blockId: "products",
    icon: "pencil-square",
    formId: "edit-product",
    requiresConfirm: false,
    usageWeight: 6,
  },
  {
    id: "delete-product",
    label: "Delete Product",
    description: "Remove a product from inventory",
    keywords: ["delete", "remove", "product", "archive"],
    category: "inventory",
    blockId: "products",
    icon: "trash",
    formId: "delete-product",
    requiresConfirm: true,
  },
  {
    id: "adjust-stock",
    label: "Adjust Stock",
    description: "Increase or reduce stock levels",
    keywords: ["stock", "adjust", "quantity", "restock", "reduce"],
    category: "inventory",
    blockId: "products",
    icon: "scale",
    formId: "edit-product",
    requiresConfirm: false,
  },
  {
    id: "add-client",
    label: "Add Client",
    description: "Create a new customer profile",
    keywords: ["add", "client", "customer", "contact", "new"],
    category: "clients",
    blockId: "clients",
    icon: "user-plus",
    formId: "add-client",
    requiresConfirm: false,
    usageWeight: 8,
  },
  {
    id: "edit-client",
    label: "Edit Client",
    description: "Update client information",
    keywords: ["edit", "update", "client", "customer", "change"],
    category: "clients",
    blockId: "clients",
    icon: "user-pen",
    formId: "edit-client",
    requiresConfirm: false,
  },
  {
    id: "add-invoice",
    label: "Add Invoice",
    description: "Create an invoice for a client",
    keywords: ["add", "invoice", "bill", "charge", "create"],
    category: "invoices",
    blockId: "incomes",
    icon: "receipt",
    requiresConfirm: false,
    fallbackEntryType: "system-log",
  },
  {
    id: "mark-paid",
    label: "Mark Invoice Paid",
    description: "Set invoice status to paid",
    keywords: ["paid", "mark", "invoice", "payment", "settle"],
    category: "invoices",
    blockId: "incomes",
    icon: "wallet-check",
    formId: "mark-paid",
    requiresConfirm: false,
    fallbackEntryType: "system-log",
  },
  {
    id: "add-order",
    label: "Add Order",
    description: "Create a new order",
    keywords: ["add", "order", "sale", "new", "purchase"],
    category: "orders",
    blockId: "orders",
    icon: "shopping-cart-plus",
    formId: "add-order",
    requiresConfirm: false,
    usageWeight: 7,
  },
  {
    id: "cancel-order",
    label: "Cancel Order",
    description: "Cancel an existing order",
    keywords: ["cancel", "order", "remove", "void"],
    category: "orders",
    blockId: "orders",
    icon: "x-circle",
    formId: "cancel-order",
    requiresConfirm: true,
  },
  {
    id: "fulfil-order",
    label: "Fulfil Order",
    description: "Mark order as fulfilled",
    keywords: ["fulfil", "ship", "complete", "order", "send"],
    category: "orders",
    blockId: "orders",
    icon: "truck",
    formId: "fulfil-order",
    requiresConfirm: false,
  },
  {
    id: "user-settings",
    label: "User Settings",
    description: "Update your profile and preferences",
    keywords: ["settings", "user", "profile", "account", "preferences"],
    category: "settings",
    blockId: "settings",
    icon: "user-cog",
    formId: "user-settings",
    requiresConfirm: false,
    usageWeight: 9,
  },
  {
    id: "org-settings",
    label: "Organization Settings",
    description: "Update business-level settings",
    keywords: ["org", "organization", "business", "company", "settings"],
    category: "settings",
    blockId: "settings",
    icon: "building-cog",
    formId: "org-settings",
    requiresConfirm: false,
    usageWeight: 9,
  },
  {
    id: "view-logs",
    label: "View Logs",
    description: "Open activity history in chat",
    keywords: ["logs", "history", "activity", "record", "audit"],
    category: "logs",
    blockId: "chat",
    icon: "clipboard-list",
    requiresConfirm: false,
    usageWeight: 5,
  },
];
