import type { BlockConfig, BlockId } from "@/blocks/types";

const CRUD_SCOPES = ["view", "create", "edit", "delete"] as const;

export const BLOCK_REGISTRY: Record<BlockId, BlockConfig> = {
  chat: {
    id: "chat",
    label: "Chat",
    description: "Contextual chat and command interface.",
    tier: "mandatory",
    icon: "chat-bubble-left-right",
    hardDependencies: [],
    softDependencies: [],
    enhancedBy: ["reports", "orders", "products", "clients", "incomes", "outputs"],
    permissionScopes: [...CRUD_SCOPES],
    dataTypes: ["chat_message"],
    paletteActions: ["view-logs"],
    navigationEntry: { label: "Chat", icon: "chat-bubble-left-right", route: "/dashboard/chat", order: 1 },
    onDisable: "hide",
  },
  notifications: {
    id: "notifications",
    label: "Notifications",
    description: "System and organization notifications.",
    tier: "mandatory",
    icon: "bell",
    hardDependencies: [],
    softDependencies: [],
    enhancedBy: ["orders", "clients", "settings"],
    permissionScopes: ["view"],
    dataTypes: ["notification"],
    paletteActions: ["view-logs"],
    navigationEntry: { label: "Notifications", icon: "bell", route: "/dashboard/notifications", order: 2 },
    onDisable: "hide",
  },
  settings: {
    id: "settings",
    label: "Settings",
    description: "Organization and user configuration.",
    tier: "mandatory",
    icon: "cog-6-tooth",
    hardDependencies: [],
    softDependencies: [],
    enhancedBy: ["employees", "suppliers"],
    permissionScopes: [...CRUD_SCOPES],
    dataTypes: ["organization_settings", "user_settings"],
    paletteActions: ["user-settings", "org-settings"],
    navigationEntry: { label: "Settings", icon: "cog-6-tooth", route: "/dashboard/settings", order: 99 },
    onDisable: "hide",
  },
  reports: {
    id: "reports",
    label: "Reports",
    description: "Dashboard insights generated from active blocks.",
    tier: "core",
    icon: "document-chart-bar",
    hardDependencies: [],
    softDependencies: ["products", "clients", "orders", "incomes", "outputs"],
    enhancedBy: [],
    permissionScopes: ["view"],
    dataTypes: ["report"],
    paletteActions: [],
    navigationEntry: { label: "Reports", icon: "document-chart-bar", route: "/dashboard/reports", order: 10 },
    onDisable: "hide",
  },
  products: {
    id: "products",
    label: "Products",
    description: "Inventory catalog and stock management.",
    tier: "core",
    icon: "cube",
    hardDependencies: [],
    softDependencies: ["suppliers"],
    enhancedBy: ["orders", "reports"],
    permissionScopes: [...CRUD_SCOPES],
    dataTypes: ["product"],
    paletteActions: ["add-product", "edit-product", "delete-product", "adjust-stock"],
    navigationEntry: { label: "Products", icon: "cube", route: "/dashboard/products", order: 30 },
    onDisable: "hide",
  },
  clients: {
    id: "clients",
    label: "Clients",
    description: "Client records and relationship history.",
    tier: "core",
    icon: "users",
    hardDependencies: [],
    softDependencies: ["orders", "incomes"],
    enhancedBy: ["orders", "incomes", "reports"],
    permissionScopes: [...CRUD_SCOPES],
    dataTypes: ["client"],
    paletteActions: ["add-client", "edit-client"],
    navigationEntry: { label: "Clients", icon: "users", route: "/dashboard/clients", order: 40 },
    onDisable: "hide",
  },
  orders: {
    id: "orders",
    label: "Orders",
    description: "Sales order pipeline and fulfillment tracking.",
    tier: "core",
    icon: "shopping-cart",
    hardDependencies: ["products"],
    softDependencies: ["clients", "incomes"],
    enhancedBy: ["incomes", "reports", "clients"],
    permissionScopes: [...CRUD_SCOPES],
    dataTypes: ["order"],
    paletteActions: ["add-order", "cancel-order", "fulfil-order", "mark-paid"],
    navigationEntry: { label: "Orders", icon: "shopping-cart", route: "/dashboard/orders", order: 20 },
    onDisable: "hide",
  },
  incomes: {
    id: "incomes",
    label: "Incomes",
    description: "Income ledger and cash-in tracking.",
    tier: "core",
    icon: "arrow-trending-up",
    hardDependencies: [],
    softDependencies: ["orders", "clients"],
    enhancedBy: ["reports", "clients"],
    permissionScopes: [...CRUD_SCOPES],
    dataTypes: ["income"],
    paletteActions: ["add-invoice", "mark-paid"],
    navigationEntry: { label: "Incomes", icon: "arrow-trending-up", route: "/dashboard/transactions", order: 50 },
    onDisable: "hide",
  },
  outputs: {
    id: "outputs",
    label: "Outputs",
    description: "Expense ledger and cash-out tracking.",
    tier: "core",
    icon: "arrow-trending-down",
    hardDependencies: [],
    softDependencies: ["suppliers"],
    enhancedBy: ["reports"],
    permissionScopes: [...CRUD_SCOPES],
    dataTypes: ["output"],
    paletteActions: [],
    navigationEntry: { label: "Outputs", icon: "arrow-trending-down", route: "/dashboard/transactions", order: 51 },
    onDisable: "hide",
  },
  suppliers: {
    id: "suppliers",
    label: "Suppliers",
    description: "Supplier and vendor records.",
    tier: "future",
    icon: "building-storefront",
    hardDependencies: [],
    softDependencies: ["products", "outputs"],
    enhancedBy: ["products", "outputs"],
    permissionScopes: [...CRUD_SCOPES],
    dataTypes: ["supplier"],
    paletteActions: [],
    onDisable: "hide",
  },
  employees: {
    id: "employees",
    label: "Employees",
    description: "Staff records linked to operational workflows.",
    tier: "future",
    icon: "users",
    hardDependencies: [],
    softDependencies: ["outputs", "orders"],
    enhancedBy: ["outputs", "orders"],
    permissionScopes: [...CRUD_SCOPES],
    dataTypes: ["employee"],
    paletteActions: [],
    onDisable: "hide",
  },
};

export const MANDATORY_BLOCKS: BlockId[] = Object.values(BLOCK_REGISTRY)
  .filter((block) => block.tier === "mandatory")
  .map((block) => block.id);
